### PR TITLE
修复cve以及check检查问题

### PR DESCRIPTION
**Pull request by 2511689622**

### CODE REVIEW

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.24%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#10060;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/99c7d59e96c74d5c963cbf39a9049518/f0a4c0ff47bc47cbb253bceacd33e8f3">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.24%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/99c7d59e96c74d5c963cbf39a9049518/6b19f82cd1a24d3fbc858681ff482ec3">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.24%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/99c7d59e96c74d5c963cbf39a9049518/5f8e9a1648b849e39fb97029bc80c45e">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.24%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/99c7d59e96c74d5c963cbf39a9049518/5b2d04b9c367474597ffb43656079469">点击跳转</a></td>
</tr>
</table>

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
开始门禁检查，等门禁检查通过后可以合入

**Comment by shishupei** [comment]
<table style="border-collapse: collapse" border=1>
    <tr>
        <th>检查项</th>
        <th>状态</th>
        <th>日志</th>
    </tr>

<tr>
    <td>DT覆盖率</td>
    <td>0.24%</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_dt覆盖率.html">查看日志</a></td>
</tr>

<tr>
    <td>敏感信息扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_敏感信息扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>Check代码检查</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_Check代码检查.html">查看日志</a></td>
</tr>

<tr>
    <td>安全编码扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_安全编码扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>开源代码漏洞扫描</td>
    <td>&#9989;</td>
    <td><a href="https://opensourceways-ci.test.osinfra.cn/log/EasySoftwareService/73/73_开源代码漏洞扫描.html">查看日志</a></td>
</tr>

<tr>
    <td>流水线链接</td>
    <td colspan="2"><a href="https://devcloud.cn-north-4.huaweicloud.com/cicd/project/3a76c1785dda4b13a399937d1978f240/pipeline/detail/99c7d59e96c74d5c963cbf39a9049518/ab86e5debe544b5ba4b2de90993c8df2">点击跳转</a></td>
</tr>
</table>

**Review by zhongjun2 — APPROVED** [review]

**Pull request merged**
